server-ha-postgres/Dockerfile
server-ha-postgres/update-standalone-ha.xsl
server-mysql/Dockerfile
server-postgres/Dockerfile
server-postgres/changeDatabase.xsl

- Fixed parent hierarchy for keycloak-ha-postgres, and incremented to next version 1.2.0.CR1
- Added config update of standalone-ha.xml in keycloak-postgres, and keycloak-mysql
Note: jboss/keycloak:1.2.0.CR1 has to be released first for the changed Dockerfiles to build.

Keycloak ha postgres

---

server/Dockerfile

jboss/base uses CentOS 7 as of Jul 1, 2015. Fix keycloak image to support CentOS 7.
Currently, docker build fails because it cannot find the jq package. This pull request fixes by adding `epel-release` before installing `jq`.
```
$ docker build --no-cache server
Sending build context to Docker daemon 5.632 kB
Sending build context to Docker daemon 
Step 0 : FROM jboss/base-jdk:7
---> 6adb355a1864
Step 1 : ENV KEYCLOAK_VERSION 1.2.0.Final
---> Running in 2b468477bb51
---> e536d3fea6bf
Removing intermediate container 2b468477bb51
Step 2 : USER root
---> Running in 0c8f5acd67fa
---> abfd759fd030
Removing intermediate container 0c8f5acd67fa
Step 3 : RUN yum install -y jq && yum clean all
---> Running in d13413232015
Loaded plugins: fastestmirror
Determining fastest mirrors
* base: …
```

Add support for CentOS 7 base image

---

server-postgres/changeDatabase.xsl

The POSTGRES_USER variable changed to POSTGRES_USERNAME, and this is breaking the API in README.md.
This is causing breaks in automated updates in production environments, that expects to use POSTGRES_USER, the default variable from postgres container.

Fix POSTGRES_USER bug that doesn't fit the API in README.md

---

server-postgres/changeDatabase.xsl

It seems that the stylesheet to update the standalon(-ha).xml references to datasources namespace with version 2.0 but it actually is 3.0 at least with Keycloak v1.3.1.Final.

Fix to datasources namespace (v2.0 -> v3.0)

---

server-mysql/changeDatabase.xsl

The xml namespace for datasources was changed from 'urn:jboss:domain:datasources:2.0' to 'urn:jboss:domain:datasources:3.0' with wildfly 9. This change was not considered in the xml transformation file so that the H2 datasource was not changed to the mysql one.

Xml namespace for datasource changed

---

server/Dockerfile

Enables signals passing from startup script to JVM, making sure wildfly
has a clean shutdown where container is stopped.
Signed-off-by: Tiago Pires <tandrepires@gmail.com>

Wildfly clean shutdown.

---

server-ha-postgres/keycloak-server.json

Following the "Running Keycloak cluster with Docker" post (http://blog.keycloak.org/2015/04/running-keycloak-cluster-with-docker.html) I was unable to get the server to start, receiving a NullPointerException at org.keycloak.models.sessions.infinispan.initializer.OfflineUserSessionLoader.init(OfflineUserSessionLoader.java:25). This was also noticed by one of the commenters on the post.
Looking at the code, it seems as though a UserSessionPersister was coming back null.
I have added to keycloak-server.json the following:
"userSessionPersister": {
"provider" : "jpa"
},
which seems to fix the problem.

Add userSessionPersister configuration to allow the server to start.

---

examples/docker-entrypoint.sh
server/docker-entrypoint.sh

When interactively running the current containers `CTRL+C` does not exit wildfly since the signal is not passed on to the process. Making sure that wildfly is the main process fixes this: http://www.projectatomic.io/docs/docker-image-author-guidance/

Add exec in bash wrapper scripts so that signals propogate

---

server/setLogLevel.xsl

And still no DEBUG/TRACE logging by default on the console? Workaround:
```
docker exec -it <mycontainer> tail -f /opt/jboss/keycloak/standalone/log/server.log
```

Upgraded loggins subsystem version

---

adapter-wildfly/Dockerfile

Is it possible to update the base Wildfly image for Keycloak adapter to the version 10.1.0.Final?

update base image to wildfly10.1.0.Final

---

server/Dockerfile
server/README.md

I've added the ability to configure proxy address forwarding and documented how to do this in the README.
The easiest way to test it is to set a SSL edge proxy and see if the Admin Console link on the /auth page links to an http or https address.  This is easiest to set up in OpenShift as an edge terminated route.

Making Proxy address forwarding configurable

---

server/Dockerfile
server/README.md

Move the `sed` command below the definition of `JBOSS_HOME`.  It appears
standalone.xml doesn't exist at the point when the `sed` was run.
Additionally the environment variable `JBOSS_HOME` was not defined.
Also added the equals sign to the `server/README.md`. Without an equals
sign docker assumes true is the container name which causes it to fail.

Fix proxy address forwarding layer

---

server-mysql/changeDatabase.xsl
server-postgres/changeDatabase.xsl

Datasources namespace in Keycloak configuration files is : 
```xml
<subsystem xmlns="urn:jboss:domain:datasources:5.0">
```
The .xsl files used by Dockerfile to customize Keycloak configuration file still use 4.0 version :
```xml
<xsl:stylesheet version="2.0"
xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
xmlns:ds="urn:jboss:domain:datasources:4.0">
```
This PR correct the problems by updating namespace versions in .xsl files

Change namespace version for datasources

---

server-mysql/README.md
server-postgres/README.md

The passwords used by default to access a MySQL or PostgreSQL database
do not match the ones listed in the corresponding README files. Correct
the README files.

Correct documented default database passwords

---

adapter-wildfly/Dockerfile

Per @stianst 's comment on #74 , just adding the SAML adapter to the same wildfly server as the OIDC adapter.
Going to leave the old PR out there - some folks that only use one or the other might not like having the additoinal subsystems installed on the wildfly server...

add SAML adapter to wildfly image

---

server-openshift/Dockerfile

The last change in the main image broke the build of the `keycloak-openshift` image.
This PR fixes the problem.
@stianst or anyone with commit rights, would it be possible to merge this ?
if possible it would be great if a new build with an incremented tag (`3.3.0.CR2-3` ?) could be made available soon.
We (the project I'm currently working on) are currently blocked in a release process due to this broken build, and we might be forced to build the image ourselves and host it in some other official place, which IMO would not be the best solution.
Signed-off-by: David Festal <dfestal@redhat.com>

Fix the broken build of the `keycloak-openshift` image

---

server/README.md

According to [postgres official image docs](https://hub.docker.com/_/postgres/), environment variable for database name is POSTGRES_DB instead of POSTGRES_DATABASE, and no ROOT_POSTGRES_PASSWORD is available.

Fix postgres container environment variables

---

server/cli/loglevel.cli

I would have filed this just as an issue, but issues aren't available for this project.

Fix typo from org.keycloack to org.keycloak

---

server-openshift/README.md

Fixed some typos for 'Postgres' in the REAMDE.md file

Fix typos for 'Postgres'

---

server/Dockerfile

In March 2018 the Postgres team did release the `42.2.2` as its current version

Using latest postgres JDBC 4.2 driver

---

server/Dockerfile
server/databases/mysql/module.xml

I also sent an email to the keycloak dev list to discuss this. https://lists.jboss.org/pipermail/keycloak-dev/2018-May/010815.html

Bumps MySQL Driver version to 5.1.46 to support MySQL 8

---

server/cli/proxy.cli

Ensure correct ip addresses show up in logging when https is used between proxy and keycloak.

https-listener also honor proxy-address-forwarding setting

---

openshift-examples/keycloak-https-mutual-tls.json
openshift-examples/keycloak-https.json
server/README.md
server/tools/cli/jgroups/discovery/default.cli
server/tools/docker-entrypoint.sh
server/tools/jgroups.sh

https://issues.jboss.org/browse/KEYCLOAK-7582
This PR adds clustering support for the Keycloak Docker image. As the matter of fact, it makes allows to use any discovery protocol with custom configuration.
Here's how it works:
* The configuration scripts pick up `JGROUPS_DISCOVERY_PROTOCOL` and `JGROUPS_DISCOVERY_PROPERTIES` variables.
* In the next step, the main entry point script passes those two configuration variables to `jgroups.sh` script.
* The script adjusts the variables and invokes `cli/jgroups/discovery/default.cli` (or a cli file with an exact protocol name if it exists; but in most of the cases, the `default.cli` should be enough).
* The CLI script modifies `standalone-ha.xml`. It removed the default discovery protocol and replaces it with the one specified above.
* The final …

KEYCLOAK-7582 Discovery protocol support

---

server/README.md
server/tools/cli/standalone-configuration.cli
server/tools/cli/standalone-ha-configuration.cli
server/tools/cli/theme.cli

This PR would permit to modify the welcome theme without the need to extends the docker image.
It simply update `standalone(-ha).xml` with an env value for `welcomeTheme` attribute (defaults to keycloak).

add possibility to change welcome theme by env variable

---

server/tools/x509.sh

I was using the `X509_CA_BUNDLE` feature when I noticed in the logs that it `"Failed to import certificates from system's Java CA certificate bundle into Keycloak truststore!"`.
I pulled the container down and built the truststore manually like the script does, and it succeeded. I checked the return code and it was 0, so I believe this is backwards.

Fixing truststore import message

---

server/README.md
server/tools/autorun.sh
server/tools/docker-entrypoint.sh

This change will allow extending images to simply drop files in `/opt/jboss/keycloak/tools/docker-entrypoint.d` to have them ran on container startup. Special support for `.cli` files is provided.
This is useful for, in our case, simple tweaks to the `standalone.xml`.

Support a docker-entrypoint.d directory

---

README.md

It looks like mysql/pgsql images were merged into the main one and it's likely that's the reason why those links are 404s now

Remove dead links from README.md

---

server/tools/autorun.sh

In #176 this directory was introduced, then renamed. This PR will also update the error message to display the correct directory name.

Fix error message path in autorun

---

server/README.md
server/tools/cli/theme.cli

Providing the ability to set the global default theme within a container image by setting an environment variable KEYCLOAK_DEFAULT_THEME with the name of the custom theme.
If environment variable is not set, theme will default to keycloak. Same behaviour as the KEYCLOAK_WELCOME_THEME.
Changes tested by :
1. extending container image with custom theme and setting environment variable. Launch container and verify custom theme is set. 
2. executing base container to ensure default is still keycloak theme.

KEYCLOAK-9715 add KEYCLOAK_DEFAULT_THEME to set global default theme

---

server/README.md
server/tools/docker-entrypoint.sh

Adds a ```file_env``` function and support for using the environment variables ```KEYCLOAK_USER_FILE``` and ```KEYCLOAK_PASSWORD_FILE``` to the Dockerfile.
Also adds a comment to each of the Docker compose example files to use these if Docker Swarm secrets support is available.

KEYCLOAK-9787: Support for file-based provisioning of Keycloak admin username and password

---

server/tools/docker-entrypoint.sh

https://issues.jboss.org/browse/KEYCLOAK-9767
This commit allows running the Keycloak image with Podman. The root cause, why it didn't work was that we were binding to a wrong interface - `fe80::5003:8eff:fefa:3e53%tap0`. I corrected this with this PR.
You may test this using `podman run slaskawi/keycloak-tmp`.
@Nowheresly - This PR may affect you as you worked previously on https://github.com/jboss-dockerfiles/keycloak/pull/156. Could you please verify if it works for you?
@stianst - Could you please test it with your environment? for a short test, please use `podman run slaskawi/keycloak-tmp`. For a longer one, you'd need to rebuild the image.

KEYCLOAK-9767 Bind to proper interface

---

README.md

Issue: [KEYCLOAK-10285](https://issues.jboss.org/browse/KEYCLOAK-10285)
Fix the url link in the `README.md` file to use the updated versions of the Docker Hub urls.
`https://cloud.docker.com/u/jboss/repository/docker/jboss/keycloak`
`https://hub.docker.com/r/jboss/keycloak`

KEYCLOAK-10285: Fix Docker hub links on README.md

---

server/README.md
server/tools/cli/jgroups/discovery/default.cli
server/tools/jgroups.sh

We have a clustered keycloak deployment on Google Kubernetes Engine. Since Google Cloud Platform does not support UDP multicast we use TCP.
The configuration option introduced in this PR greatly simplifies the configuration. The JGroups transport stack can be changed using the environment variable JGROUPS_TRANSPORT_STACK

KEYCLOAK-10198 KEYCLOAK-10199: Allow JGroups transport stack configuration

---

server/README.md
server/tools/cli/databases/postgres/change-database.cli
server/tools/docker-entrypoint.sh

jdbc allow connection fail-over for postgres. Please refer to https://jdbc.postgresql.org/documentation/head/connect.html

KEYCLOAK-9881: add postgres connection fail-over url

---

server/README.md
server/tools/docker-entrypoint.sh
server/tools/jgroups.sh

The parsing step of JGROUPS_DISCOVERY_PROPERTIES in jgroups.sh makes
it impossible to correctly specify properties whose value includes an
`=` character. Some discovery protocols, such as KUBE_PING, require
properties that have an `=` in their value, i.e., `{labels=>app=keycloak}`

KEYCLOAK-10789 Add optional unparsed JGROUPS_DISCOVERY_PROPERTIES_DIRECT

---

openshift-examples/keycloak-https-mutual-tls.json
server/README.md
server/tools/cli/x509-truststore.cli
server/tools/x509.sh

https://issues.jboss.org/browse/KEYCLOAK-10652
This Pull Request allows adding multiple CA Bundles into `X509_CA_BUNDLE` and imports generated trust store into Truststore SPI. Here's an example:
```bash
X509_CA_BUNDLE=/var/run/secrets/kubernetes.io/serviceaccount/service-ca.crt /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
When running in Kubernetes with the example above, Keycloak will automatically be able to call other services deployed in OpenShift (using `service-ca.crt`) as we as the Kubernetes API server (using `ca.crt`).

KEYCLOAK-10652 Truststore optimizations

---

server/tools/docker-entrypoint.sh

This change is to the recently added file_env function in the docker-entrypoint.sh script. The update is to only export the variable if a value is defined.

KEYCLOAK-10152: Only export variables when value defined

---

server/README.md
server/tools/cli/metrics/db.cli
server/tools/cli/metrics/http.cli
server/tools/cli/metrics/jgroups.cli
server/tools/docker-entrypoint.sh
server/tools/statistics.sh

The CLI is run at runtime, when all the other configuration is done (jgroups and database). This allows to have all this configuration in an unique file instead of in all others cli commands.

KEYCLOAK-10120: enable statistics with env variable

---

server/README.md

In version 5.0.0 default values for environment variables `DB_USER` and `DB_PASSWORD` were `keycloak` and `password`, which is no longer the case in 6.0.0.
Starting from version 6.0.0 not setting `DB_USER` will cause an error: "WFLYCTL0113: '' is an invalid value for parameter user-name. Values must have a minimum length of 1 characters".
So I think the information in https://hub.docker.com/r/jboss/keycloak and https://github.com/jboss-dockerfiles/keycloak/blob/master/server/README.md is misleading and should be updated according to the changes in new versions.

Fixed outdated information in README.md

---

docker-compose-examples/README.md
docker-compose-examples/keycloak-mariadb-jdbc-ping.yml

https://issues.jboss.org/browse/KEYCLOAK-11148
This Pull Request contains a preview version of `JDBC_PING` integration with Maria DB. The discovery protocol configuration is done by adjusting `JGROUPS_DISCOVERY_PROTOCOL` and `JGROUPS_DISCOVERY_PROPERTIES`.

KEYCLOAK-11148 JDBC_PING example with Maria DB

---

server/README.md

KEYCLOAK-11124
Adding dns. makes the example JGROUPS_DISCOVERY_PROTOCOL not fail.

KEYCLOAK-11124 add dns. to example JGroup protocol

---

server/README.md
server/tools/cli/infinispan/cache-owners.cli
server/tools/docker-entrypoint.sh
server/tools/infinispan.sh

Issue KEYCLOAK-7582 introduced support for standalone-ha type of clusters via i.e. DNS_PING. Unfortunately the number of owners to the distributed-cache is "1" by default causing data-loss at shutdown of any node. See: https://www.keycloak.org/docs/5.0/server_installation/#_replication
Especially in a container environment like on Kubernetes / OpenShift it just seems natural to have an owner count of 2 or 3 to allow not just for downtime-free, but also data-loss-free rolling updates / reconfiguration of a Keycloak cluster.
Configuration of the owners count was already implemented by in a previous PR by https://github.com/rayscunningham regarding clustering - https://github.com/jboss-dockerfiles/keycloak/pull/96 - but this was closed in favor of …

KEYCLOAK-10151 Allow configuration of owner count for the distributed caches

---

server/tools/docker-entrypoint.sh

Shell script do not permit call a function declared bellow, this causing error to run the image "opt/jboss/tools/docker-entrypoint.sh: line 138: append_port_db_addr: command not found"

Correct the script to work with postgre

---

server/Dockerfile
server/tools/build-keycloak.sh

[KEYCLOAK-10059] Use ubi8-minimal instead of base-jdk as base image

---

server/Dockerfile
server/tools/build-keycloak.sh

[KEYCLOAK-11457] Backport of ubi8-minimal changes

---

server/tools/docker-entrypoint.sh

Make the user/password handling more safe for whitespace in user or password. This wraps them both in ".

[KEYCLOAK-11622] Make the user/password handling more safe for whitespace

---

server/Dockerfile
server/tools/build-keycloak.sh

- Update of released versions
Depends on https://github.com/keycloak/keycloak-containers/pull/227

Backport of [KEYCLOAK-11636] Switched to ubi8 image that doesn't require a redhat account and added the jboss user

---

server/README.md

Without the absolute path, we get an error from the docker engine.
```
> docker exec <CONTAINER> keycloak/bin/add-user-keycloak.sh -u user -p password
OCI runtime exec failed: exec failed: container_linux.go:346: starting container process caused "exec: \"keycloak/bin/add-user-keycloak.sh\": stat keycloak/bin/add-user-keycloak.sh: no such file or directory": unknown
```

Fix the path for the add-user-keycloak.sh script

---

server/README.md
server/tools/cli/files-plaintext-vault.cli
server/tools/docker-entrypoint.sh
server/tools/vault.sh

This PR requires Keycloak version 8.0.0 where the vault support is present.

KEYCLOAK-11419 Vault support in Docker

---

server/tools/x509.sh

[KEYCLOAK-12306](https://issues.jboss.org/browse/KEYCLOAK-12306)
The current implementation of the Keycloak Container image generates (and uses!) an empty Keystore if `/etc/x509/https` exists and is empty. This results in making HTTPS port (`8443`) unusable (as there are no common ciphers)

KEYCLOAK-12306 Do not generate Keystore on empty /etc/x509/https dir

---

server/tools/build-keycloak.sh

With KEYCLOAK-10059 the base image has been changed to ubi8-minimal.
Since ubi8-minimal does not ship with a user named 'jboss', the user
will be created in the startup scripts. However, the previously used
image jboss/base-jdk also ships with a group named 'jboss', the
ubi8-minimal image does not. With KEYCLOAK-10059 this group
does not get created
For backwards compatibility a group named 'jboss' has been added and
the user 'jboss' has been associated as a member of that group.

KEYCLOAK-12387 Add jboss group

---

server/README.md

Updating documentation with reference to most recently used base image for `server` image creation (`ubi8-minimal`)

Update 'server' README.md - ubi-minimal as base image

---

server/README.md

[KEYCLOAK-12737](https://issues.redhat.com/browse/KEYCLOAK-12737)
This Pull Request contains a small clarification in the manual, that most of the custom scripts should use offline mode.

KEYCLOAK-12737 Offline scripts clarification in manual

---

server/Dockerfile

This pull request installs `glibc-langpack-en` package because locale files was not installed.

[KEYCLOAK-12879] Google identity provider doesn't handle non-ascii characters

---

server/tools/build-keycloak.sh

[KEYCLOAK-13020](https://issues.redhat.com/browse/KEYCLOAK-13020)
This Pull Request uses a more restrictive way of setting permissions proposed by @douglaspalmer in https://github.com/keycloak/keycloak-containers/pull/258. 
You may play with it using this image: `docker.io/slaskawi/keycloak:KEYCLOAK-13020-2`
Unfortunately there are some cons to this approach. It doesn't fully fix [KEYCLOAK-13020](https://issues.redhat.com/browse/KEYCLOAK-13020). Users will always need to run this container with a user, who uses group id equal to `0` (root). This way, they will simulate, how OpenShift does it: https://docs.openshift.com/container-platform/3.3/creating_images/guidelines.html

KEYCLOAK-13020 Permissions update

---

server/tools/docker-entrypoint.sh

When KEYCLOAK_FRONTEND_URL and KEYCLOAK_HOSTNAME environment variables are both set, the command line is wrong because of a missing space. 
Example: 
```
java -D[Standalone] -server -Xms64m -Xmx512m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Djboss.modules.system.pkgs=org.jboss.byteman -Djava.awt.headless=true --add-exports=java.base/sun.nio.ch=ALL-UNNAMED --add-exports=jdk.unsupported/sun.misc=ALL-UNNAMED --add-exports=jdk.unsupported/sun.reflect=ALL-UNNAMED -Dorg.jboss.boot.log.file=/opt/jboss/keycloak/standalone/log/server.log -Dlogging.configuration=file:/opt/jboss/keycloak/standalone/configuration/logging.properties -jar /opt/jboss/keycloak/jboss-modules.jar -mp /opt/jboss/keycloak/modules org.jboss.as.standalone …
```

KEYCLOAK-13391 Error accessing Keycloak when KEYCLOAK_FRONTEND_URL and KEYCLOAK_HOSTNAME are both set

---

docker-compose-examples/README.md
docker-compose-examples/keycloak-postgres-jdbc-ping.yml

added a new example to run keycloak in HA mode with postgres database and jdbc_ping discovery protocol

KEYCLOAK-12947 new docker compose example

---

server/README.md

I see that a lot of people were having this issue but with no resolution, what happens is by default the key generated by lets encrypt tools is writen as `700` which is correct. However when mounting the cert/key into the container, the container tools mount the files as root, meaning when the container is run as the jboss user it the `x509.sh` script cannot read the key and generates an empty keystore.
This makes the container start up fine but they you get weird errors like this:
```
error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure
```

update tls config readme to clarify usage with container tools

---

server/tools/x509.sh

Add message about key permissions if ${KEYSTORES_STORAGE}/${JKS_KEYSTORE_FILE} is not created.
When starting with something like "docker run .... -v .../key.pem:/etc/x509/https/tls.key quay.io/keycloak/keycloak:latest" if the key (${KEYSTORES_STORAGE}/${JKS_KEYSTORE_FILE}) is not created, for some reasons including permissions issues, no message is displayed and SSL is started in a broken state. This shows a warning message to help identify the issue.

x509.sh: add message about key permissions

---

server/README.md

https://issues.redhat.com/browse/KEYCLOAK-14690
This Pull Request clarifies that we don't support `docker start` and `docker stop` commands. See https://groups.google.com/d/msg/keycloak-dev/I3qfqTtVmvw/j5RtiBb5AgAJ

KEYCLOAK-14690 Clarify Docker start and stop commands

---

keycloak-init-container/extensions.sh

This is a slight refactor of the extensions.sh script.
Report extension download failure when the curl response code is different than 200. For example, if github.com is currently down and the extension can not be downloaded.
Previously, download failure was ignored and KeyCloak was started without the required plugin. 
Jira associated with the issue: https://issues.redhat.com/browse/INTLY-8355

INTLY-8355 Better error logs on failed extension download

---

docker-compose-examples/keycloak-mariadb-jdbc-ping.yml
server/tools/cli/jgroups/discovery/JDBC_PING.cli

[KEYCLOAK-12892](https://issues.redhat.com/browse/KEYCLOAK-12892)
Our `JDBC_PING` examples use a generic JNDI Datasource attribute. As mentioned in [WFLY-12948](https://issues.redhat.com/browse/WFLY-12948), we should use a dedicated attribute for this.

KEYCLOAK-12892 Use dedicated datasource attribute for JDBC_PING

---

server/README.md
server/tools/docker-entrypoint.sh

This fixes a "duplicate resource error" when restarting a container with a
JGROUPS_DISCOVERY_PROTOCOL, caused by attempting to re-run the configuration
scripts. https://issues.redhat.com/browse/KEYCLOAK-13094
Used @kplantjr's suggestion in comments of #264.
Compose file used for testing:
```yaml
version: '3'
services:
database:
image: postgres
environment:
POSTGRES_USER: keycloak
POSTGRES_PASSWORD: insecure
keycloak:
image: keycloak-local:fix-1
depends_on:
- database
ports:
- '8080:8080'
environment:
DB_VENDOR: postgres
DB_ADDR: database
DB_USER: keycloak
DB_PASSWORD: insecure
JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
JGROUPS_DISCOVERY_PROPERTIES: datasource_jndi_name=java:jboss/datasources/KeycloakDS,info_writer_sleep_time=1000
```

Allow container to be stopped and started

---

server/tools/docker-entrypoint.sh

This allows custom startup scripts to edit all configuration created automatically.

[KEYCLOAK-15900] The docker-entrypoint should run the autorun.sh as last command

---

server/tools/cli/files-plaintext-vault.cli

According to the [documentation](https://www.keycloak.org/docs/latest/server_admin/index.html#kubernetes-openshift-files-plaintext-vault-provider) the `<spi>` has the `<default-provider>` attribute to select the provider for the vault.
That value seems required to be able to use the vault with OpenShift.

[KEYCLOAK-15899] Set default-provider value for spi vault

---

keycloak-init-container/Dockerfile

- the packages are not part of ubi8-minimal image anymore
https://issues.redhat.com/browse/KEYCLOAK-16313

KEYCLOAK-16313 remove python packages uninstall code form init-container Dockerfile

---

server/README.md

Hi, 
this PR specifies the port over which https will be served when using the keystore generation feature.

add tls port to documentation

---

server/README.md

I've created a discussion on the mailing list: [Documentation PR: Describe how to connect to Keycloak using a java debugger](https://groups.google.com/g/keycloak-dev/c/yGM22HIkSls)
And a JIRA issue: [[KEYCLOAK-16506] Document docker configuration to allow attaching a Java debugger - Red Hat Issue Tracker](https://issues.redhat.com/browse/KEYCLOAK-16506)
@slaskawi - on keycloak-dev, you asked to be pinged about this

KEYCLOAK-16506 README: docker envs for Java debugger

---

keycloak-init-container/Dockerfile

During the image respin I have spot the issue. This is the upstream fix.
https://issues.redhat.com/browse/KEYCLOAK-17833

KEYCLOAK-17833 keycloak init image does not pick package updates while respin

---

keycloak-init-container/container.yaml

Without a compose section, the `microdnf update` present in the Dockerfile can result in unsigned RPMs being pulled into the image, resulting in an invalid image

CIAM-1672 Set compose section in init container.yaml to avoid unsigned RPMs
