adapter-wildfly/Dockerfile
=> fixed curl to download correct adapter resource

server-mongo/changeDatabase.jq
keycloak-mongo broken for Docker
=> KEYCLOAK-2248

adapter-wildfly/Dockerfile
updating wildfly version at least to 9.0.2 (didn't test WF 10 yet)
=> updating from Wildfly 9.0.1 to 10.0.0

adapter-wildfly/cccp.yml, server-ha-postgres/cccp.yml, server-postgres/cccp.yml, server/cccp.yml
This is for the purpose of building this container on the centos container pipeline.
=> Added cccp.yml files for building container on container pipeline.

server-mysql/README.md
=> make sure README reflects the actual Code

server-openshift/Dockerfile
I am basing this PR off of matzew's PR here : https://github.com/jboss-dockerfiles/wildfly/pull/42
I've tested it on the 3.6 alpha release of Origin by using the Dockerfile in a source build.
=> Setting permissions so that this container will work in OpenShift

server-postgres/Dockerfile
Apologies, fix error introduced by https://github.com/jboss-dockerfiles/keycloak/pull/82
Related JIRA: https://issues.jboss.org/browse/KEYCLOAK-5418
=> Fix error in retrieving Postgres JDBC module

docker-compose-examples/keycloak-mysql.yml, docker-compose-examples/keycloak-postgres.yml, server/README.md, server/cli/databases/mariadb/change-database.cli, server/cli/databases/mysql/change-database.cli, server/cli/databases/postgres/change-database.cli, server/docker-entrypoint.sh
Add a variable environment **POSTGRES_SSL** to specify ssl connections
=> Add JDBC parameters as environment variable

docker-compose-examples/keycloak-postgres.yml
Data is not persisted without `/data`
=> Change PostgreSQL data path

server/README.md, server/tools/docker-entrypoint.sh
Resolves [KEYCLOAK-7061](https://issues.jboss.org/browse/KEYCLOAK-7061).
=> Added support and documentation for importing realms.

gatekeeper/Dockerfile
This PR depends on https://issues.jboss.org/browse/KEYCLOAK-7266
=> [KEYCLOAK-7177] Docker image for Gatekeeper

server/tools/build-keycloak.sh
=> Download JDBC drivers using https

server/tools/build-keycloak.sh
=> Fix Maven downloads

server/README.md
KEYCLOAK-10082 include docs for exporting Realm from docker container
=> KEYCLOAK-10082 include docs for exporting Realm from docker container

server/README.md
I tried the manual yesterday - it doesn't work if u don't specify credentials of DB owner.
=> Added DB credentials to PostgreSQL sample

server/tools/docker-entrypoint.sh
Not having a JIRA for this. If needed for this typo I can open one
=> fix typo for db ports

server/tools/cli/x509-truststore.cli, server/tools/x509.sh
https://issues.jboss.org/browse/KEYCLOAK-11170
=> KEYCLOAK-11170 Create truststore SPI even when there is SSL Context

server/README.md
Fixes some typos and formatting issues
=> [KEYCLOAK-11682] Fix some typos and formatting

gatekeeper/Dockerfile
Tested building the image locally.
=> KEYCLOAK-11590 Add unprivileged user

extensions-init-container/Dockerfile, extensions-init-container/Makefile, extensions-init-container/README.md, extensions-init-container/extensions.py
Adds everything required to build the init container used by the Keycloak Operator to download and install extensions.
=> add extensions init container image

server/README.md, server/tools/cli/hostname.cli, server/tools/docker-entrypoint.sh
=> KEYCLOAK-11728 New default hostname provider

server/tools/docker-entrypoint.sh
I ran https://github.com/koalaman/shellcheck to see if it could be improved and found some minor stuff that would make if more safe. Also added `-e` to make it fail if any subcommand fails.
More details in the JIRA ticket.
https://issues.jboss.org/browse/KEYCLOAK-11696
=> [KEYCLOAK-11696] Improvements of docker-entrypoint.sh

docker-compose-examples/keycloak-mariadb-jdbc-ping.yml, docker-compose-examples/keycloak-mssql.yml, docker-compose-examples/keycloak-mysql.yml, docker-compose-examples/keycloak-oracle.yml, docker-compose-examples/keycloak-postgres.yml, openshift-examples/keycloak-https-mutual-tls.json, openshift-examples/keycloak-https.json
[KEYCLOAK-12629](https://issues.redhat.com/browse/KEYCLOAK-12629)
This Pull Request adds a healthcheck for MariaDB and upgrades all images to `latest`.
=> KEYCLOAK-12629 Add MariaDB Healthcheck and refresh all images

openshift-examples/README.md
=> KEYCLOAK-11803 Add instructions for configuring vault in openshift image

gatekeeper/Dockerfile
see https://issues.redhat.com/browse/KEYCLOAK-12901
=> [KEYCLOAK-12901] Switch to ubi8-minimal

README.md
=> missing period

server/tools/build-keycloak.sh
=> Fix build for 10

server/tools/cli/databases/mssql/change-database.cli
adds support for setting the DB SCHEMA for MSSQL DBs
=> [KEYCLOAK-11709] add DB_SCHEMA support for MSSQL

keycloak-init-container/Dockerfile, keycloak-init-container/container.yaml, keycloak-init-container/content_sets.yml, keycloak-init-container/productize.sh
https://issues.redhat.com/browse/KEYCLOAK-13616
Similarly to the Keycloak Operator, this Pull Request synchronizes upstream and downstream by providing all files we need in the downstream along with `productize.sh` file.
=> KEYCLOAK-13616 Added OSBS files and adjusted Dockerfile for prod

server/tools/build-keycloak.sh
This currently fails because keycloak-source also matches keycloak-*
=> Fix building from source

keycloak-init-container/productize.sh
This Pull Request introduces changes necessary for Delivery Repos.
=> KEYCLOAK-13616 Update for delivery repos

server/README.md, server/tools/docker-entrypoint.sh
This is a proposal to introduce support for JAVA_OPTS_APPEND environment variable. The corresponding JIRA ticket: https://issues.redhat.com/browse/KEYCLOAK-14495
=> KEYCLOAK-14495 Introduce support for JAVA_OPTS_APPEND

server/README.md
=> define -> defined

server-x/Dockerfile, server-x/README.md, server-x/tools/docker-entrypoint.sh
=> [KEYCLOAK-11336] - Server.x docker image

keycloak-init-container/container.yaml
=> Add ppc64le platform to keycloak-init-container

keycloak-init-container/productize.sh
=> KEYCLOAK-16039 Build Init Container fails on bad image repo parsing

server-x/Dockerfile, server-x/probes/liveness.sh, server-x/probes/readiness.sh
These scripts just call the smallrye health endpoints via curl. Nothing complicated.
=> KEYCLOAK-15886 Add health probe scripts to quarkus container

server-x/Dockerfile, server/Dockerfile
=> Fix URLs to KC

server/tools/autorun.sh
Hello,
here is the PR for https://issues.redhat.com/browse/KEYCLOAK-17029
=> KEYCLOAK-17029: skipping directories during autorun.sh

CONTRIBUTING.md, README.md
=> #336 Reflect migration from JIRA to GH Issues in the repo

.github/workflows/release-container.yml
=> GitHub Action to publish containers
